LEFT_HAND:
- ACTION_NAME: 张开
  POSITION:
  - 255
  - 70
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: 捏合5CM
  POSITION:
  - 165
  - 70
  - 165
  - 165
  - 255
  - 255
  - 113
  - 255
  - 255
  - 88
- ACTION_NAME: 捏合1CM
  POSITION:
  - 150
  - 70
  - 155
  - 155
  - 255
  - 255
  - 113
  - 255
  - 255
  - 88
- ACTION_NAME: 握3CM物品
  POSITION:
  - 113
  - 70
  - 85
  - 85
  - 85
  - 85
  - 85
  - 255
  - 255
  - 88
- ACTION_NAME: 准备抓握
  POSITION:
  - 255
  - 70
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 121
- ACTION_NAME: 拇指弯曲
  POSITION:
  - 35
  - 140
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 30
- ACTION_NAME: 食指弯曲
  POSITION:
  - 255
  - 70
  - 0
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: shishi
  POSITION:
  - 85
  - 30
  - 255
  - 0
  - 0
  - 255
  - 0
  - 0
  - 0
  - 66
RIGHT_HAND:
- ACTION_NAME: 张开
  POSITION:
  - 255
  - 70
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
- ACTION_NAME: 捏合5CM
  POSITION:
  - 165
  - 70
  - 165
  - 165
  - 255
  - 255
  - 113
  - 255
  - 255
  - 88
- ACTION_NAME: 捏合1CM
  POSITION:
  - 150
  - 70
  - 155
  - 155
  - 255
  - 255
  - 113
  - 255
  - 255
  - 88
- ACTION_NAME: 准备抓握
  POSITION:
  - 255
  - 70
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 255
  - 121
